//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_NHANVIEN
    {
        public int ID { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string HanhDong { get; set; }
    }
}
