//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLNHASACHEntities : DbContext
    {
        public QLNHASACHEntities()
            : base("name=QLNHASACHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DbSet<CHITIETPHIEUNHAP> CHITIETPHIEUNHAPs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<NXB> NXBs { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<TACGIA> TACGIAs { get; set; }
        public virtual DbSet<THELOAI> THELOAIs { get; set; }
        public virtual DbSet<LOG_HOADON> LOG_HOADON { get; set; }
        public virtual DbSet<LOG_NHANVIEN> LOG_NHANVIEN { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CHITIETDONHANG> CHITIETDONHANGs { get; set; }
        public virtual DbSet<DONDATHANG> DONDATHANGs { get; set; }
        public virtual DbSet<v_DanhSachSachFull> v_DanhSachSachFull { get; set; }
    
        [DbFunction("QLNHASACHEntities", "fn_TimKiemKhachHang")]
        public virtual IQueryable<fn_TimKiemKhachHang_Result> fn_TimKiemKhachHang(string tuKhoa)
        {
            var tuKhoaParameter = tuKhoa != null ?
                new ObjectParameter("TuKhoa", tuKhoa) :
                new ObjectParameter("TuKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiemKhachHang_Result>("[QLNHASACHEntities].[fn_TimKiemKhachHang](@TuKhoa)", tuKhoaParameter);
        }
    
        [DbFunction("QLNHASACHEntities", "fn_TimKiemSach")]
        public virtual IQueryable<fn_TimKiemSach_Result> fn_TimKiemSach(string tuKhoa)
        {
            var tuKhoaParameter = tuKhoa != null ?
                new ObjectParameter("TuKhoa", tuKhoa) :
                new ObjectParameter("TuKhoa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fn_TimKiemSach_Result>("[QLNHASACHEntities].[fn_TimKiemSach](@TuKhoa)", tuKhoaParameter);
        }
    
        public virtual ObjectResult<sp_BaoCaoNhapHangTheoNXB_Result> sp_BaoCaoNhapHangTheoNXB(Nullable<int> thang, Nullable<int> nam)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("Thang", thang) :
                new ObjectParameter("Thang", typeof(int));
    
            var namParameter = nam.HasValue ?
                new ObjectParameter("Nam", nam) :
                new ObjectParameter("Nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoNhapHangTheoNXB_Result>("sp_BaoCaoNhapHangTheoNXB", thangParameter, namParameter);
        }
    
        public virtual ObjectResult<sp_CapNhatThongTinKhach_Result> sp_CapNhatThongTinKhach(Nullable<int> maKH, string hoTen, string diaChi, string email)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CapNhatThongTinKhach_Result>("sp_CapNhatThongTinKhach", maKHParameter, hoTenParameter, diaChiParameter, emailParameter);
        }
    
        public virtual int sp_ChuyenDoiVaXoaTheLoai(Nullable<int> maTheLoaiCu, Nullable<int> maTheLoaiMoi)
        {
            var maTheLoaiCuParameter = maTheLoaiCu.HasValue ?
                new ObjectParameter("MaTheLoaiCu", maTheLoaiCu) :
                new ObjectParameter("MaTheLoaiCu", typeof(int));
    
            var maTheLoaiMoiParameter = maTheLoaiMoi.HasValue ?
                new ObjectParameter("MaTheLoaiMoi", maTheLoaiMoi) :
                new ObjectParameter("MaTheLoaiMoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChuyenDoiVaXoaTheLoai", maTheLoaiCuParameter, maTheLoaiMoiParameter);
        }
    
        public virtual int sp_Cursor_DoanhThu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Cursor_DoanhThu");
        }
    
        public virtual ObjectResult<sp_DoanhThuTheoNgay_Result> sp_DoanhThuTheoNgay(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("TuNgay", tuNgay) :
                new ObjectParameter("TuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("DenNgay", denNgay) :
                new ObjectParameter("DenNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DoanhThuTheoNgay_Result>("sp_DoanhThuTheoNgay", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<sp_DoanhThuTheoNhanVien_Result> sp_DoanhThuTheoNhanVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DoanhThuTheoNhanVien_Result>("sp_DoanhThuTheoNhanVien");
        }
    
        public virtual ObjectResult<sp_DoiDiemGiamGia_Result> sp_DoiDiemGiamGia(Nullable<int> maKH, Nullable<int> diemMuonDoi)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var diemMuonDoiParameter = diemMuonDoi.HasValue ?
                new ObjectParameter("DiemMuonDoi", diemMuonDoi) :
                new ObjectParameter("DiemMuonDoi", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DoiDiemGiamGia_Result>("sp_DoiDiemGiamGia", maKHParameter, diemMuonDoiParameter);
        }
    
        public virtual int sp_HuyPhieuNhap(Nullable<int> maPN)
        {
            var maPNParameter = maPN.HasValue ?
                new ObjectParameter("MaPN", maPN) :
                new ObjectParameter("MaPN", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HuyPhieuNhap", maPNParameter);
        }
    
        public virtual int sp_NhanVien_Sua(Nullable<int> maNV, string hoTen, string sDT, string chucVu)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NhanVien_Sua", maNVParameter, hoTenParameter, sDTParameter, chucVuParameter);
        }
    
        public virtual int sp_TaoHoaDon(Nullable<int> maKH, Nullable<int> maNV)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoHoaDon", maKHParameter, maNVParameter);
        }
    
        public virtual int sp_TaoHoaDon_Transaction(Nullable<int> maKH, Nullable<int> maNV, Nullable<decimal> tongTien)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoHoaDon_Transaction", maKHParameter, maNVParameter, tongTienParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_TaoPhieuNhapMoi(Nullable<int> maNXB, Nullable<int> maNV)
        {
            var maNXBParameter = maNXB.HasValue ?
                new ObjectParameter("MaNXB", maNXB) :
                new ObjectParameter("MaNXB", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_TaoPhieuNhapMoi", maNXBParameter, maNVParameter);
        }
    
        public virtual int sp_ThemChiTietHoaDon(Nullable<int> maHD, Nullable<int> maSach, Nullable<int> soLuong)
        {
            var maHDParameter = maHD.HasValue ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(int));
    
            var maSachParameter = maSach.HasValue ?
                new ObjectParameter("MaSach", maSach) :
                new ObjectParameter("MaSach", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChiTietHoaDon", maHDParameter, maSachParameter, soLuongParameter);
        }
    
        public virtual ObjectResult<sp_ThemKhachHangMoi_Result> sp_ThemKhachHangMoi(string hoTen, string sDT, string diaChi, string email)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThemKhachHangMoi_Result>("sp_ThemKhachHangMoi", hoTenParameter, sDTParameter, diaChiParameter, emailParameter);
        }
    
        public virtual int sp_ThemNhanVien(string hoTen, Nullable<System.DateTime> ngaySinh, string sDT, string chucVu, string matKhau)
        {
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("HoTen", hoTen) :
                new ObjectParameter("HoTen", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", hoTenParameter, ngaySinhParameter, sDTParameter, chucVuParameter, matKhauParameter);
        }
    
        public virtual int sp_ThemSachMoi(string tenSach, Nullable<int> maTL, Nullable<int> maTG, Nullable<int> maNXB, Nullable<int> namXB, Nullable<decimal> giaNhap, Nullable<decimal> giaBan, string moTa)
        {
            var tenSachParameter = tenSach != null ?
                new ObjectParameter("TenSach", tenSach) :
                new ObjectParameter("TenSach", typeof(string));
    
            var maTLParameter = maTL.HasValue ?
                new ObjectParameter("MaTL", maTL) :
                new ObjectParameter("MaTL", typeof(int));
    
            var maTGParameter = maTG.HasValue ?
                new ObjectParameter("MaTG", maTG) :
                new ObjectParameter("MaTG", typeof(int));
    
            var maNXBParameter = maNXB.HasValue ?
                new ObjectParameter("MaNXB", maNXB) :
                new ObjectParameter("MaNXB", typeof(int));
    
            var namXBParameter = namXB.HasValue ?
                new ObjectParameter("NamXB", namXB) :
                new ObjectParameter("NamXB", typeof(int));
    
            var giaNhapParameter = giaNhap.HasValue ?
                new ObjectParameter("GiaNhap", giaNhap) :
                new ObjectParameter("GiaNhap", typeof(decimal));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(decimal));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemSachMoi", tenSachParameter, maTLParameter, maTGParameter, maNXBParameter, namXBParameter, giaNhapParameter, giaBanParameter, moTaParameter);
        }
    
        public virtual ObjectResult<sp_ThongKe_SoLuongHoaDon_Result> sp_ThongKe_SoLuongHoaDon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKe_SoLuongHoaDon_Result>("sp_ThongKe_SoLuongHoaDon");
        }
    
        public virtual int sp_ThongKeHoaDon()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThongKeHoaDon");
        }
    
        public virtual ObjectResult<sp_ThongKeSoSachNhap_Result> sp_ThongKeSoSachNhap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThongKeSoSachNhap_Result>("sp_ThongKeSoSachNhap");
        }
    
        public virtual ObjectResult<sp_TichDiem_Result> sp_TichDiem(Nullable<int> maKH, Nullable<int> diemMuonThem)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var diemMuonThemParameter = diemMuonThem.HasValue ?
                new ObjectParameter("DiemMuonThem", diemMuonThem) :
                new ObjectParameter("DiemMuonThem", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TichDiem_Result>("sp_TichDiem", maKHParameter, diemMuonThemParameter);
        }
    
        public virtual ObjectResult<sp_XemChiTietLichSuMuaHang_Result> sp_XemChiTietLichSuMuaHang(Nullable<int> maKH)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_XemChiTietLichSuMuaHang_Result>("sp_XemChiTietLichSuMuaHang", maKHParameter);
        }
    
        public virtual int sp_XoaNhanVien(Nullable<int> maNV)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaNhanVien", maNVParameter);
        }
    }
}
