//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_DanhSachSachFull
    {
        public int MaSach { get; set; }
        public string TenSach { get; set; }
        public string TenTL { get; set; }
        public string TenTG { get; set; }
        public string TenNXB { get; set; }
        public Nullable<int> SoLuongTon { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
    }
}
